server:
  port: 8095
  servlet:
    context-path: /demand


spring:
  # 服务名称
  application:
    name: demand

  servlet:
    multipart:
      location: /upload
      max-file-size: 50MB #设置允许单个文件上传的大小
      max-request-size: 100MB #设置允许上传的总的文件的大小

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqljiushiyigedashab.+-*
    url: jdbc:mysql://43.142.160.234:3306/edccloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

  #  redis配置
  redis:
    host: 43.142.160.234
    port: 6379
    password: redis2jiu41ge+da+sb
    lettuce:
      pool:
        max-active: 8
        min-idle: 2
        max-wait: 100


    #  # 注册中心
    #  cloud:
    #    nacos:
    #      server-addr: http://43.142.160.234:8848
    #      username: nacos
    #      password: nacoshaishikeyide0

    # mybatis-plus
    #mybatis-plus:
    #  configuration:
    #    关闭驼峰转换
    #    map-underscore-to-camel-case: true

    #logging:
    #  level:
    # 下面路径为feign的全路径地址，可自定义记录某个类/包的日志级别
#    com.edcccd.basic.basic.feign: debug

myBasePath: F:/ssss/
#myRootPath: /home/mysave/
userPath: ccd/