server:
  port: 8091

spring:
  # 服务名称
  application:
    name: accountservice

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqljiushiyigedashab.+-*
    url: jdbc:mysql://43.142.160.234:3306/edccloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

  # 注册中心
  cloud:
    nacos:
      server-addr: http://43.142.160.234:8848
      username: nacos
      password: nacoshaishikeyide0

# mybatis-plus
mybatis-plus:
  configuration:
    #    关闭驼峰转换
    map-underscore-to-camel-case: false